_wandb:
    value:
        cli_version: 0.19.6
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 41
                - 55
            "2":
                - 1
                - 41
                - 55
            "3":
                - 2
                - 16
                - 23
                - 55
            "4": 3.11.10
            "5": 0.19.6
            "8":
                - 3
                - 5
            "12": 0.19.6
            "13": windows-amd64
architecture:
    value: NeuralNetwork
dataset:
    value: MNIST
epochs:
    value: 10
learning_rate:
    value: 0.001
