_wandb:
    value:
        cli_version: 0.19.6
        m:
            - "1": train_loss_epoch
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
            - "1": train_loss_step
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": epoch
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": val_loss_step
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": avg_val_loss
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": val_loss_epoch
              "5": 2
              "6":
                - 1
                - 3
              "7": []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 9
                - 41
                - 55
                - 103
                - 106
            "2":
                - 1
                - 9
                - 41
                - 55
                - 103
                - 106
            "3":
                - 7
                - 13
                - 23
                - 55
                - 66
            "4": 3.11.10
            "5": 0.19.6
            "8":
                - 3
                - 5
            "12": 0.19.6
            "13": windows-amd64
